<?php

/**
 * BaseMunicipio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estado_id
 * @property string $nombre
 * @property Estado $Estado
 * @property Doctrine_Collection $Parroquia
 * @property Doctrine_Collection $Centro
 * @property Doctrine_Collection $Beneficiario
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getEstadoId()     Returns the current record's "estado_id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Estado              getEstado()       Returns the current record's "Estado" value
 * @method Doctrine_Collection getParroquia()    Returns the current record's "Parroquia" collection
 * @method Doctrine_Collection getCentro()       Returns the current record's "Centro" collection
 * @method Doctrine_Collection getBeneficiario() Returns the current record's "Beneficiario" collection
 * @method Municipio           setId()           Sets the current record's "id" value
 * @method Municipio           setEstadoId()     Sets the current record's "estado_id" value
 * @method Municipio           setNombre()       Sets the current record's "nombre" value
 * @method Municipio           setEstado()       Sets the current record's "Estado" value
 * @method Municipio           setParroquia()    Sets the current record's "Parroquia" collection
 * @method Municipio           setCentro()       Sets the current record's "Centro" collection
 * @method Municipio           setBeneficiario() Sets the current record's "Beneficiario" collection
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Alexis Limongi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipio');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasMany('Parroquia', array(
             'local' => 'id',
             'foreign' => 'municipio_id'));

        $this->hasMany('Centro', array(
             'local' => 'id',
             'foreign' => 'municipio_id'));

        $this->hasMany('Beneficiario', array(
             'local' => 'id',
             'foreign' => 'municipio_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}