<?php

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $Municipio
 * @property Doctrine_Collection $Centro
 * @property Doctrine_Collection $Beneficiario
 * @property Doctrine_Collection $Atencion
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method Doctrine_Collection getUser()         Returns the current record's "User" collection
 * @method Doctrine_Collection getMunicipio()    Returns the current record's "Municipio" collection
 * @method Doctrine_Collection getCentro()       Returns the current record's "Centro" collection
 * @method Doctrine_Collection getBeneficiario() Returns the current record's "Beneficiario" collection
 * @method Doctrine_Collection getAtencion()     Returns the current record's "Atencion" collection
 * @method Estado              setId()           Sets the current record's "id" value
 * @method Estado              setNombre()       Sets the current record's "nombre" value
 * @method Estado              setUser()         Sets the current record's "User" collection
 * @method Estado              setMunicipio()    Sets the current record's "Municipio" collection
 * @method Estado              setCentro()       Sets the current record's "Centro" collection
 * @method Estado              setBeneficiario() Sets the current record's "Beneficiario" collection
 * @method Estado              setAtencion()     Sets the current record's "Atencion" collection
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as User', array(
             'refClass' => 'UserEstado',
             'local' => 'estado_id',
             'foreign' => 'user_id'));

        $this->hasMany('Municipio', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Centro', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Beneficiario', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Atencion', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}