<?php

/**
 * BaseBeneficiario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ci
 * @property string $nombre
 * @property string $apellido
 * @property date $fnacimiento
 * @property enum $sexo
 * @property enum $estado_civ
 * @property integer $estado_id
 * @property integer $municipio_id
 * @property integer $parroquia_id
 * @property string $direccion
 * @property string $telf1
 * @property string $telf2
 * @property string $mail1
 * @property string $familiar
 * @property string $telf_fam
 * @property enum $fallecido
 * @property Estado $Estado
 * @property Municipio $Municipio
 * @property Parroquia $Parroquia
 * @property Doctrine_Collection $Atencion
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getCi()           Returns the current record's "ci" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getApellido()     Returns the current record's "apellido" value
 * @method date                getFnacimiento()  Returns the current record's "fnacimiento" value
 * @method enum                getSexo()         Returns the current record's "sexo" value
 * @method enum                getEstadoCiv()    Returns the current record's "estado_civ" value
 * @method integer             getEstadoId()     Returns the current record's "estado_id" value
 * @method integer             getMunicipioId()  Returns the current record's "municipio_id" value
 * @method integer             getParroquiaId()  Returns the current record's "parroquia_id" value
 * @method string              getDireccion()    Returns the current record's "direccion" value
 * @method string              getTelf1()        Returns the current record's "telf1" value
 * @method string              getTelf2()        Returns the current record's "telf2" value
 * @method string              getMail1()        Returns the current record's "mail1" value
 * @method string              getFamiliar()     Returns the current record's "familiar" value
 * @method string              getTelfFam()      Returns the current record's "telf_fam" value
 * @method enum                getFallecido()    Returns the current record's "fallecido" value
 * @method Estado              getEstado()       Returns the current record's "Estado" value
 * @method Municipio           getMunicipio()    Returns the current record's "Municipio" value
 * @method Parroquia           getParroquia()    Returns the current record's "Parroquia" value
 * @method Doctrine_Collection getAtencion()     Returns the current record's "Atencion" collection
 * @method Beneficiario        setId()           Sets the current record's "id" value
 * @method Beneficiario        setCi()           Sets the current record's "ci" value
 * @method Beneficiario        setNombre()       Sets the current record's "nombre" value
 * @method Beneficiario        setApellido()     Sets the current record's "apellido" value
 * @method Beneficiario        setFnacimiento()  Sets the current record's "fnacimiento" value
 * @method Beneficiario        setSexo()         Sets the current record's "sexo" value
 * @method Beneficiario        setEstadoCiv()    Sets the current record's "estado_civ" value
 * @method Beneficiario        setEstadoId()     Sets the current record's "estado_id" value
 * @method Beneficiario        setMunicipioId()  Sets the current record's "municipio_id" value
 * @method Beneficiario        setParroquiaId()  Sets the current record's "parroquia_id" value
 * @method Beneficiario        setDireccion()    Sets the current record's "direccion" value
 * @method Beneficiario        setTelf1()        Sets the current record's "telf1" value
 * @method Beneficiario        setTelf2()        Sets the current record's "telf2" value
 * @method Beneficiario        setMail1()        Sets the current record's "mail1" value
 * @method Beneficiario        setFamiliar()     Sets the current record's "familiar" value
 * @method Beneficiario        setTelfFam()      Sets the current record's "telf_fam" value
 * @method Beneficiario        setFallecido()    Sets the current record's "fallecido" value
 * @method Beneficiario        setEstado()       Sets the current record's "Estado" value
 * @method Beneficiario        setMunicipio()    Sets the current record's "Municipio" value
 * @method Beneficiario        setParroquia()    Sets the current record's "Parroquia" value
 * @method Beneficiario        setAtencion()     Sets the current record's "Atencion" collection
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBeneficiario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('beneficiario');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ci', 'integer', 10, array(
             'type' => 'integer',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 10,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('apellido', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('fnacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('sexo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'M',
              1 => 'F',
             ),
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('estado_civ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Solter@',
              1 => 'Casad@',
              2 => 'Viud@',
              3 => 'Divorciad@',
              4 => 'Separad@',
              5 => 'Conviviente',
             ),
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telf1', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telf2', 'string', 120, array(
             'type' => 'string',
             'notnull' => false,
             'notblank' => false,
             'minlength' => 0,
             'length' => 120,
             ));
        $this->hasColumn('mail1', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('familiar', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telf_fam', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('fallecido', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Si',
              1 => 'No',
             ),
             'notnull' => true,
             'notblank' => true,
             'default' => 'No',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasMany('Atencion', array(
             'local' => 'id',
             'foreign' => 'beneficiario_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}