<?php

/**
 * BaseCentro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estado_id
 * @property integer $municipio_id
 * @property integer $parroquia_id
 * @property string $direccion
 * @property string $nombre
 * @property string $responsable
 * @property string $telf1
 * @property string $telf2
 * @property string $mail1
 * @property string $mail2
 * @property integer $adultos_msalud
 * @property integer $adultos_fsalud
 * @property integer $adultos_msocial
 * @property integer $adultos_fsocial
 * @property integer $adultos_f
 * @property integer $adultos_m
 * @property integer $adultos_t
 * @property long $latitud
 * @property long $longitud
 * @property string $type
 * @property Estado $Estado
 * @property Municipio $Municipio
 * @property Parroquia $Parroquia
 * @property Doctrine_Collection $Atencion
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getEstadoId()        Returns the current record's "estado_id" value
 * @method integer             getMunicipioId()     Returns the current record's "municipio_id" value
 * @method integer             getParroquiaId()     Returns the current record's "parroquia_id" value
 * @method string              getDireccion()       Returns the current record's "direccion" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getResponsable()     Returns the current record's "responsable" value
 * @method string              getTelf1()           Returns the current record's "telf1" value
 * @method string              getTelf2()           Returns the current record's "telf2" value
 * @method string              getMail1()           Returns the current record's "mail1" value
 * @method string              getMail2()           Returns the current record's "mail2" value
 * @method integer             getAdultosMsalud()   Returns the current record's "adultos_msalud" value
 * @method integer             getAdultosFsalud()   Returns the current record's "adultos_fsalud" value
 * @method integer             getAdultosMsocial()  Returns the current record's "adultos_msocial" value
 * @method integer             getAdultosFsocial()  Returns the current record's "adultos_fsocial" value
 * @method integer             getAdultosF()        Returns the current record's "adultos_f" value
 * @method integer             getAdultosM()        Returns the current record's "adultos_m" value
 * @method integer             getAdultosT()        Returns the current record's "adultos_t" value
 * @method long                getLatitud()         Returns the current record's "latitud" value
 * @method long                getLongitud()        Returns the current record's "longitud" value
 * @method string              getType()            Returns the current record's "type" value
 * @method Estado              getEstado()          Returns the current record's "Estado" value
 * @method Municipio           getMunicipio()       Returns the current record's "Municipio" value
 * @method Parroquia           getParroquia()       Returns the current record's "Parroquia" value
 * @method Doctrine_Collection getAtencion()        Returns the current record's "Atencion" collection
 * @method Centro              setId()              Sets the current record's "id" value
 * @method Centro              setEstadoId()        Sets the current record's "estado_id" value
 * @method Centro              setMunicipioId()     Sets the current record's "municipio_id" value
 * @method Centro              setParroquiaId()     Sets the current record's "parroquia_id" value
 * @method Centro              setDireccion()       Sets the current record's "direccion" value
 * @method Centro              setNombre()          Sets the current record's "nombre" value
 * @method Centro              setResponsable()     Sets the current record's "responsable" value
 * @method Centro              setTelf1()           Sets the current record's "telf1" value
 * @method Centro              setTelf2()           Sets the current record's "telf2" value
 * @method Centro              setMail1()           Sets the current record's "mail1" value
 * @method Centro              setMail2()           Sets the current record's "mail2" value
 * @method Centro              setAdultosMsalud()   Sets the current record's "adultos_msalud" value
 * @method Centro              setAdultosFsalud()   Sets the current record's "adultos_fsalud" value
 * @method Centro              setAdultosMsocial()  Sets the current record's "adultos_msocial" value
 * @method Centro              setAdultosFsocial()  Sets the current record's "adultos_fsocial" value
 * @method Centro              setAdultosF()        Sets the current record's "adultos_f" value
 * @method Centro              setAdultosM()        Sets the current record's "adultos_m" value
 * @method Centro              setAdultosT()        Sets the current record's "adultos_t" value
 * @method Centro              setLatitud()         Sets the current record's "latitud" value
 * @method Centro              setLongitud()        Sets the current record's "longitud" value
 * @method Centro              setType()            Sets the current record's "type" value
 * @method Centro              setEstado()          Sets the current record's "Estado" value
 * @method Centro              setMunicipio()       Sets the current record's "Municipio" value
 * @method Centro              setParroquia()       Sets the current record's "Parroquia" value
 * @method Centro              setAtencion()        Sets the current record's "Atencion" collection
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCentro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('centro');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('direccion', 'string', 300, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 300,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('responsable', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telf1', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telf2', 'string', 120, array(
             'type' => 'string',
             'notnull' => false,
             'notblank' => false,
             'minlength' => 0,
             'length' => 120,
             ));
        $this->hasColumn('mail1', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('mail2', 'string', 120, array(
             'type' => 'string',
             'notnull' => false,
             'notblank' => false,
             'minlength' => 0,
             'length' => 120,
             ));
        $this->hasColumn('adultos_msalud', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_fsalud', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_msocial', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_fsocial', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_f', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_m', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('adultos_t', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('latitud', 'long', null, array(
             'type' => 'long',
             'notnull' => false,
             ));
        $this->hasColumn('longitud', 'long', null, array(
             'type' => 'long',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'Gerogranja' => 
             array(
              'type' => 'Gerogranja',
             ),
             'Ambulatorio' => 
             array(
              'type' => 'Ambulatorio',
             ),
             'Residencial' => 
             array(
              'type' => 'Residencial',
             ),
             'Aldea' => 
             array(
              'type' => 'Aldea',
             ),
             'Refugio' => 
             array(
              'type' => 'Refugio',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasMany('Atencion', array(
             'local' => 'id',
             'foreign' => 'centro_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}