<?php

/**
 * BaseUserEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $estado_id
 * 
 * @method integer    getUserId()    Returns the current record's "user_id" value
 * @method integer    getEstadoId()  Returns the current record's "estado_id" value
 * @method UserEstado setUserId()    Sets the current record's "user_id" value
 * @method UserEstado setEstadoId()  Sets the current record's "estado_id" value
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Alexis Limongi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_estado');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}