<?php

/**
 * Beneficiario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Beneficiario extends BaseBeneficiario
{
        public function  __toString() {
        return $this->getNombre().' '.$this->getApellido();
        }

       public function  save(Doctrine_Connection $conn = null) {
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try {

            $part = $this->getFallecido();
            if($part == 'Si'){
            $this->setDeletedAt($this->getUpdatedAt());
            }
            if($part == 'No'){
            $this->setDeletedAt(NULL);
            }
            $ret = parent::save($conn);
            $conn->commit();
            return $ret;
        }  catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }
    }


}

