<?php

/**
 * Comunasconst
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Alexis Limongi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comunasconst extends BaseComunasconst
{
}
