prod:
  url_absoluta: http://inasscentros/backend.php

dev:
  url_absoluta: http://inasscentros/backend_dev.php

all:
  limite: 15
  .ys_jquery_revolutions_plugins:
    ### To load jQuery from ajax.googleapis.com:
    ### - jquery.min.js
    #ys_jquery_path: http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
    ### - jquery.js
    #ys_jquery_path: http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js

    ### To load jQuery from localhost
    ### - Only available jquery.min.js
    ys_jquery_path: /ysJQueryRevolutionsPlugin/js/jquery/jquery-1.5.2.min.js
    ys_jquery_web_dir: ysJQueryRevolutionsPlugin
    ys_jquery_js_dir:  jquery
    ys_jquery_core: jquery-1.5.2.min.js
    ys_jquery_plugins_folder: plugins
    ys_jquery_js_folder:  js
    ys_jquery_css_folder: css
    ys_jquery_images_folder: images
    path_separattor:       '/'

  .ys_jquery_ui_plugins:
    ys_jquery_ui_web_dir:         /ysJQueryUIPlugin    #default /ysJqueryUIPlugin
    ys_jquery_ui_theme_dir:       /ysJQueryUIPlugin/css/themes          #default /css/themes
    ys_jquery_ui_js_dir:          /js/jquery/ui        #default /js/jquery/ui
    ys_jquery_ui_theme:           redmond              #default ui-lightness
    ys_jquery_ui_i18n_dir:        i18n                 #default /i18n
    ys_jquery_ui_theme_rolller:   /ysJQueryUIPlugin/js/jquery/themeswitchertool.js
    ###jquery.ui.core
    ys_jquery_ui_core_js:         [ui.core.js]
    ys_jquery_ui_core_css:        [jquery-ui-1.8.custom.css]

    ### Uses structured configuration if you use plugins.
    #ys_jquery_web_dir: ysJQueryRevolutionsPlugin
    #ys_jquery_js_dir:  jquery
    #ys_jquery_core: jquery-1.3.2.min.js
    #ys_jquery_plugins_folder: plugins
    #ys_jquery_js_folder:  js
    #ys_jquery_css_folder: css
    #ys_jquery_images_folder: images
    #path_separattor:       '/'

  sf_guard_plugin:
    success_signin_url:      main/index
    success_signout_url:     main/index
