<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/23 12:11:56
sfConfig::add(array(
  'app_ys_jquery_path' => '/ysJQueryRevolutionsPlugin/js/jquery/jquery-1.3.2.min.js',
  'app_ys_jquery_css' => '/ysJQueryRevolutionsPlugin/css',
  'app_ys_jquery_images' => '/ysJQueryRevolutionsPlugin/images',
  'app_ys_jquery_plugins_folder' => '/ysJQueryRevolutionsPlugin/js/jquery/plugins',
  'app_ys_jquery_plugins' => array (
  'auto_complete' => 
  array (
    'local' => true,
    'js_files' => 
    array (
      0 => 'jquery.autocomplete.pack.js',
      1 => 'jquery.bgiframe.min.js',
    ),
    'css_files' => 
    array (
      0 => 'jquery.autocomplete.css',
    ),
    'default_options' => 
    array (
      'oddClass' => 'ui-state-default',
      'evenClass' => 'ui-state-hover',
      'overClass' => 'ui-state-active',
    ),
  ),
),
  'app_url_absoluta' => 'http://inasscentros/frontend_dev.php',
));
