# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

new:
  credentials: [[admin, dircen, dirgero]]

edit:
  credentials: [[admin, dircen, dirgero]]

show:
  credentials: [[admin, dircen, dirgero, usersal, usercon]]

delete:
  credentials: [[admin, dircen, dirgero]]

index:
  credentials: [[admin, dircen, dirgero, usersal, usercon]]
