default:
  http_metas:
    content-type: text/html

  metas:
    title:        Sistema Automatizado para el Registro de Centros de Atención
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [login.css]

  javascripts:    []

  has_layout:     true
  layout:         login