<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/20 10:46:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=inasscentros;unix_socket=/var/run/mysqld/mysqld.sock',
  'username' => 'inasscentros',
  'password' => 'In@Sc3N#R0s',
  'name' => 'doctrine',
)),);
