<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/07/20 10:46:24
$this->security = array (
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'show' => 
  array (
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
