<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/15 18:47:41
sfConfig::add(array(
  'app_ys_jquery_path' => '/ysJQueryRevolutionsPlugin/js/jquery/jquery-1.5.2.min.js',
  'app_ys_jquery_css' => '/ysJQueryRevolutionsPlugin/css',
  'app_ys_jquery_images' => '/ysJQueryRevolutionsPlugin/images',
  'app_ys_jquery_plugins_folder' => 'plugins',
  'app_ys_jquery_plugins' => array (
  'auto_complete' => 
  array (
    'local' => true,
    'js_files' => 
    array (
      0 => 'jquery.autocomplete.pack.js',
      1 => 'jquery.bgiframe.min.js',
    ),
    'css_files' => 
    array (
      0 => 'jquery.autocomplete.css',
    ),
    'default_options' => 
    array (
      'oddClass' => 'ui-state-default',
      'evenClass' => 'ui-state-hover',
      'overClass' => 'ui-state-active',
    ),
  ),
),
  'app_limite' => 15,
  'app_ys_jquery_web_dir' => 'ysJQueryRevolutionsPlugin',
  'app_ys_jquery_js_dir' => 'jquery',
  'app_ys_jquery_core' => 'jquery-1.5.2.min.js',
  'app_ys_jquery_js_folder' => 'js',
  'app_ys_jquery_css_folder' => 'css',
  'app_ys_jquery_images_folder' => 'images',
  'app_path_separattor' => '/',
  'app_ys_jquery_ui_web_dir' => '/ysJQueryUIPlugin',
  'app_ys_jquery_ui_theme_dir' => '/ysJQueryUIPlugin/css/themes',
  'app_ys_jquery_ui_js_dir' => '/js/jquery/ui',
  'app_ys_jquery_ui_theme' => 'redmond',
  'app_ys_jquery_ui_i18n_dir' => 'i18n',
  'app_ys_jquery_ui_theme_rolller' => '/ysJQueryUIPlugin/js/jquery/themeswitchertool.js',
  'app_ys_jquery_ui_core_js' => array (
  0 => 'ui.core.js',
),
  'app_ys_jquery_ui_core_css' => array (
  0 => 'jquery-ui-1.8.custom.css',
),
  'app_sf_guard_plugin_success_signin_url' => 'main/index',
  'app_sf_guard_plugin_success_signout_url' => 'main/index',
  'app_url_absoluta' => 'http://inasscentros/backend_dev.php',
));
