<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/23 14:18:25
$this->security = array (
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dircen',
      ),
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dircen',
      ),
    ),
  ),
  'show' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dircen',
        2 => 'usersal',
        3 => 'usercon',
      ),
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dircen',
      ),
    ),
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'dircen',
        2 => 'usersal',
        3 => 'usercon',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
